language: java
jdk:
- oraclejdk8
install: true
script: |
  # only (attempt to) deploy non-pull request commits to the master branch
  if [ "$TRAVIS_PULL_REQUEST" = false ] && [ "$TRAVIS_BRANCH" = master ]; then
    mvn clean deploy
  else
    # otherwise, just run test suite
    mvn clean verify
  fi
env:
  global:
  - secure: "Qc6DiwXJHojwps7poByHdLGeybLF8NwqO+6LjY3Bwx1seUqeGVyeFD98y/sH0mjuEvBxhfA8MBAK2BhyjqtSqxgZWQeeUkf7GFlRnqwmJQvyG86ae/aapdIamfAAIog9HsqTSo8RYCYVTiKzAlLGorAC0KJwc525+IrxDeZx2hJThdPZpMmgybo53leaqB3z60yG04NZB2wOA3Fi+LmKGZvPbyO0wL1pCz04+WVXvBpuhOkSUEd/VwtVbFP0tEUBpXk8pgaSDmNqH7x0m9PapY3KOBbjVfwhRsD/nIAjZL5dyD3U8mOhXMY5Cv3ItW+taYpuH9AbmYJEUSvaf3r+qnYJ1ebm3cNRbwWnWm5Gjl65YmKa4K5RD2eu4VFn+H/bA56YLLANbQC3gGYx8WbGzeCr6uAQWaU5KTWbeiU9/oEVKK2SCBgkO4xNC14lWRVPzDRS9+FICbFsWXCHZEbcE2RgvUezSxe4kv2UJbjPbH7TqZB+2F0WOkc3DFqbBVcbeGr8CrapuFmnA/P7EN8zsoDY4uaV0D5hcwnAP04iQeRS3JJKJ61oDJLb0VuO5+mtUrZQQDg+LUWWmRJMJx4+kVVTnxhcL874MT056KwICrrB/kTu/UBM1Me7PaIYdV6VafcMe/BGQQLddugoUpVtEioeKKoRMPkeXReAwsDjAZY="
  - secure: "XiJphtnuC3yyyxY5gmDoUNEqg4ylWKNHzAd3YdTcTpfR7V7Sp1Xnzn0DtYNlR1AYAvRns+DNhLhUtBtCsdgUqRdxT7IWA/bUPb+QGL706KmNkToRX0DoEGrNOfRKfyyL7NgVGshc3mXdCaJOaBvZxUoEAZgfBJS+yF8c+UI45zZeXdNMwctoTgkZaeWCCNdGgWgEhfc4DidO40m6e7XwVXZU11TX15Co5rjrXjUYmqfdO1X0G2es/FqGwlhjAbxwPp7NNLq+F2hnyIVoLuINn9JubvO5RUvdrqCmYtv2xr3rq8gDoL+Iyt1WjVY8qEmPANm3/kPlgF3+UKya1KPmKFXs1aDi3hgE3ePPNtiNMJuNjlw4sVewPrzMat+lp75k6V3JCNeNEY5RhloTJFtcARxz0tsEQz8HqizFJ1aOO08KRzdLNpV1dXSlasN11QWaD3B3xUcDO4ug+X6w3OA339yaOhbNK2AzRB1dcRP/IzPPpe86/FWLfgYky+aQgUsC/Qyk/LEfLZo5VGqM8UVV63anSS4QCq338CfZ1KdUCNYcIewQCmbE2DvfgLfLq4BfYuGj0cUuhFRq2NauNUoIR+Azz+F4cvKM2mqYYQzmhjs66rbsgyqgn6iHmf/1Et/6BnnzIWxZ3JJMxBfuVLZdRCqS+wlmxpcmPXPoB7Bu4ZU="
sudo: false
cache:
  directories:
  - "$HOME/.m2/repository"
notifications:
  slack: conveyal:WQxmWiu8PdmujwLw4ziW72Gc